### ISSUE TITLE
Better logging of errors

### ISSUE THREAD

**Issue by trentmwillis** [trentmwillis/ember-a11y-testing#2]
Currently all errors just inject any offending HTMLElement into the error message string. This makes identifying the exact offending element difficult. Instead, we should switch to a model that logs the element separately so it can be inspected and identified.

**Comment by majew7** [comment]
Was the fix removed?

This bug fix (9505490a9), made understanding the offending element easier by improving the `A11yError` constructor function.  However, I see that e599bccbdc36940, named _"Remove old approach"_ from May 18, 2016, seems to have removed the improvement that this issue ticket was all about.

**Question)** What does "Remove old approach." mean?

Understanding the results is difficult when the console is throwing multiple errors, because I don't know the offending HTML element.
